# Generated by Django 2.1.15 on 2022-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(max_length=25)),
                ('Date', models.CharField(max_length=25)),
                ('Price', models.IntegerField()),
                ('Car', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Surname', models.CharField(max_length=25)),
                ('Patronymic', models.CharField(max_length=25)),
                ('Telephone', models.CharField(max_length=11)),
                ('Role', models.CharField(max_length=25)),
            ],
        ),
    ]
