// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OutputMotorcyclesFromDatabase.Entities
{
    public partial class Motorcycles
    {
        public int Id { get; set; }
        public string MarkName { get; set; }
        public string ModelName { get; set; }
        public string Vin { get; set; }
        public double Mileage { get; set; }
        public double Price { get; set; }
        public byte[] Image { get; set; }
    }
}